---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
#permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
kramdown:
  input: GFM

### content configuration ###
title:       "corbel"
keywords:    "corbel, jekyll, rest, github, blog, backend, oauth"
description: ""
email: dev@bq.com
source_link: "http://corbel.docs.bqws.io"
url: "http://corbel.docs.bqws.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: 
twitter_username: "jekyllrb"
github_username:  "jekyll"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
